### ISSUE TITLE
[FavoriteMedia]: Floating & clipping medias

### ISSUE THREAD

**Issue by critbees** [Dastan21/BDAddons#171]
### Discord Build

Stable

### Discord Version

Stable 171621 (b20d67a)

### Plugin Version

v1.7.0

### Steps To Reproduce

1. Have 6 or more image categories
2. Favourite an image so that it reaches the bottom of the page (it should clip underneath the 'empty space art')
3. Drag the favourite image into any of the categories
4. Click the category the image was placed in to see

### Describe the bug

An issue of having 6 (or more) categories so any saved images clip underneath the 'empty space art' (it should clip underneath the 'empty space' art, mine is arcade machines, a small character and some spiders and cobwebs, for example, to show nothing is further down on the tab). Trying to drag an image that's clipped beneath that 'empty space art' into a category renders the entire ctageory as unviewable.

It shortens the amount that you need to scroll to reach the bottom (mine was two scrolls) despite havign 115 images in the category; it makes all the thumbnails grey; there is no possible way to tell which image is which, as clicking on a randomly highlighted space sends a random image.

[The first attached image is of the blank category, the image amount, the image highlight cutting through the grey space, and how short the scroll bar is compared to the amount of images. 

The second attached image is an example of the clipping image issue, before attempting to drag it into a category.]

### Screenshots

![image](https://user-images.githubusercontent.com/124394572/216685506-c09eb079-81a0-4719-98ec-0b97d2f57cbc.png)
![Screenshot 2023-02-03 190310](https://user-images.githubusercontent.com/124394572/216685904-2f680100-6660-4f52-8c0b-c2357d8aea60.png)

**Comment by Silvia-Dragoness** [comment]
Happening to me even without having set up _any_ categories yet.  But only for still images; gifs and videos are fine.

**Comment by Dastan21** [comment]
Yup, fixed in 1.7.1
Waiting BD to approve the update before closing this issue.

**Comment by yuma-dev** [comment]
installed 1.7.1 manually due to the same error happening to me as well, bug still continues to exist

**Comment by Dastan21** [comment]
Any error/warning in the console?
Also can you please share your FavoriteMedia.config.js?

**Comment by yuma-dev** [comment]
No warnings or error in the console and this is my 
This happens when first switching to video and then to images after:
![Discord_H4WZqa2fOp](https://user-images.githubusercontent.com/76885566/217326797-0e4ae13d-523a-474d-8064-2151e9f2b60d.png)

And this is my config:
https://gist.github.com/yuma-dev/a88985514367d0a5360d8672be7ad9a8

**Comment by yuma-dev** [comment]
I did reset just all of my media and started adding them again, the ContextMenu does give it no width but even the button on the image itself gives width: 100% and that starts the issue again like shown in this gif:
![Discord_9RirASzinT](https://user-images.githubusercontent.com/76885566/217442044-4f149e81-e617-447c-9c50-d28f749a7b2a.gif)

They get saved like this in the config:

        "medias": [
            {
                "url": "https://cdn.discordapp.com/attachments/785155838545362964/1072748411394207744/I_am_currently_in_a_Discord_meme_channel.png",
                "width": "100%",
                "name": "I_am_currently_in_a_Discord_meme_channel",
                "message": "https://discord.com/channels/undefined/785155838545362964/1072748414846128210"
            },
            {
                "url": "https://cdn.discordapp.com/attachments/785155838545362964/1072748412484722698/0bce91d5d26880c291e054cff2c5473f.png",
                "width": "100%",
                "name": "0bce91d5d26880c291e054cff2c5473f",
                "message": "https://discord.com/channels/undefined/785155838545362964/1072748414846128210"
            }
        ],

**Comment by Dastan21** [comment]
What did you use to make images look like this? A plugin?

**Comment by yuma-dev** [comment]
What do you mean?

**Comment by Dastan21** [comment]
The mosaic effect, it may be caused by this.

**Comment by yuma-dev** [comment]
There is no effect or plugin causing this, if you mean how the images look in chat, that's what happens when you send the 10 pictures with one message

**Comment by Dastan21** [comment]
Well idk, they don't get wrapped the same when I upload 10 images... Are you on Discord stable/PTB/canary?

**Comment by yuma-dev** [comment]
Im on stable, this even happens when using vanilla discord web 
![msedge_Yg6hJ75tQQ](https://user-images.githubusercontent.com/76885566/217560107-e01d2f55-be30-42d7-a955-1dad8f59c190.png)

**Comment by Dastan21** [comment]
It also doesn't work on the web for me ;-;
What's your Discord stable version? Maybe it's because you're using W11

**Comment by yuma-dev** [comment]
Its Stable 172394 (287c8cd)

**Comment by yuma-dev** [comment]
But do you think that's the cause?

**Comment by Dastan21** [comment]
Just tested with a friend who has W11 and it look the same as me, so no.

**Comment by yuma-dev** [comment]
add me on discord so we dont spam github:
discord.gg/pAFhmbkK

**Comment by Silvia-Dragoness** [comment]
Multi-image posts have been organized like that for at least a few weeks.  They're even like that on mobile now.

**Comment by Dastan21** [comment]
Well, I will wait until the update lands for me to fix it.

**Comment by yuma-dev** [comment]
You can enable it via the Discord experiments

**Comment by critbees** [comment]
tested the new update regarding this issue:

![image](https://user-images.githubusercontent.com/124394572/226702194-d69d4359-4c56-4894-91db-b682a09e4c1c.png)
![image](https://user-images.githubusercontent.com/124394572/226702212-bc0e1f81-a028-44a2-9f95-a8c395edd95e.png)
![image](https://user-images.githubusercontent.com/124394572/226702729-a0503384-ad3b-41ef-874a-cfa457a23b88.png)
Making a new category seemed to cross it over with the OTHER older category (e.g. the tf2 category i made) that was bugged for me, and deleting that newly made category also deleted the tf2 category. Those images aren't unfavourited fortunately and simply display on the main image favourites tab, but appear even worse than the previous bug with it. (the media clipping beneath the dusty cowboy arace machine art also persists.) The new tf2 category I made to drop them into again only displays two images, which are always the same.
