### ISSUE TITLE
[FavoriteMedia]: Multiple Gif Categories All Share Contents

### ISSUE THREAD

**Issue by itsaxolotl** [Dastan21/BDAddons#230]
### Discord Build

PTB

### Discord Version

Stable 252471

### Plugin Version

1.8.13

### Steps To Reproduce

1. Create one gif category
2. Create second gif category
3. Add gif to either menu
4. Gif is added to both instead of just one

### Describe the bug

basically covered in the steps to reproduce, however many categories you have in one place they all share contents

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/153258247/237cf6c5-1042-4743-9581-0abbfecd15eb)

**Comment by itsaxolotl** [comment]
Apologies, I am using the standard version of discord and not PTB, not sure how that got mixed up

**Comment by itsaxolotl** [comment]
In addition to this, even when added into a category gifs persist to exist in regular favorites menu as well

**Comment by Dastan21** [comment]
Fixed in 1.8.14

**Comment by itsaxolotl** [comment]
![image](https://github.com/Dastan21/BDAddons/assets/153258247/770d1ec8-d775-47b7-a2bf-f112d433e459)
Looks like it is still happening on my end

**Comment by Dastan21** [comment]
Check plugin version, it has not been validated by BD yet.

**Comment by Dastan21** [comment]
Did you delete the categories first?

**Comment by itsaxolotl** [comment]
Yes, fully deleted categories and cleared out all gifs, then tried with a gif in trending, still showing in both categories and general favorites

**Comment by itsaxolotl** [comment]
Additionally, when deleting one category, it deletes all of them at once.

**Comment by Dastan21** [comment]
Restart Discord? It looks like the update did not apply for you.

**Comment by itsaxolotl** [comment]
Option was enabled by default and it still seems to be showing it in the tab

**Comment by itsaxolotl** [comment]
Think i got it? Ticking the option off and on again triggered it to update
